name: network_analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python>=3.6
  - pip
  - pip:
    - numpy==1.24.2
    - pandas==2.0.0
    - tqdm==4.64.1
    - matplotlib==3.7.1
    - networkx==2.5.1
    - igraph==0.10.4 
    - texttable==1.6.7
    - zstandard==0.20.0
    - graph-tools==1.11
    - seaborn==0.12.2